\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{fhnwfactsheet}[2017/03/15 v1.0 PDF-LaTeX class for FHNW fact sheets]
%\LoadClass{minimal}
\LoadClass{article}
\pagestyle{empty}
\RequirePackage{geometry}
\geometry{a4paper,twoside=false}
\geometry{width=210mm,height=297mm,outer=5mm,inner=5mm,top=5mm,bottom=5mm}

%\newcommand{\mycommand}{\sffamily}
%\newenvironment
%\DeclareOption
%\ProcessOption
%\DeclareOption{draft}{\setlength{\overfullrule}{5pt}}
%\ProcessOptions\relax
%\AtBeginDocument % Part of the preamble!
%\AtEndDocument
% Identification
% Prelimintary Declarations
% Options
% More more declarations (main work stuff)
