default:
	@latex fhnwfactsheet.ins
	@pdflatex fhnwfactsheet.dtx

clean:
	@rm -f fhnwfactsheet.aux
	@rm -f fhnwfactsheet.cls
	@rm -f fhnwfactsheet.glo
	@rm -f fhnwfactsheet.idx
	@rm -f fhnwfactsheet.log
	@rm -f fhnwfactsheet.pdf
