default:
	@latex fhnwfactsheet.ins
	@pdflatex fhnwfactsheet.dtx
	@pdflatex fhnwfactsheet-de.tex
	#@cp fhnwfactsheet.cls ../

clean:
	@rm -f fhnwfactsheet.aux
	@rm -f fhnwfactsheet.cls
	@rm -f fhnwfactsheet.glo
	@rm -f fhnwfactsheet.idx
	@rm -f fhnwfactsheet.log
	@rm -f fhnwfactsheet.pdf
	@rm -f fhnwfactsheet.dvi
	@rm -f fhnwfactsheet.tex
	@rm -f fhnwfactsheet.out
	@rm -f fhnwfactsheet.toc
	@rm -f fhnwfactsheet-de.*
	@rm -f template.*
