default:
	@latex fhnwfactsheet.ins
	@pdflatex fhnwfactsheet.dtx
	@pdflatex fhnwfactsheet-de.tex

clean:
	@rm -f fhnwfactsheet.aux
	@rm -f fhnwfactsheet.cls
	@rm -f fhnwfactsheet.glo
	@rm -f fhnwfactsheet.idx
	@rm -f fhnwfactsheet.log
	@rm -f fhnwfactsheet.pdf
	@rm -f fhnwfactsheet.dvi
	@rm -f fhnwfactsheet.tex
	@rm -f fhnwfactsheet-de.aux
	@rm -f fhnwfactsheet-de.glo
	@rm -f fhnwfactsheet-de.idx
	@rm -f fhnwfactsheet-de.log
	@rm -f fhnwfactsheet-de.pdf
	@rm -f fhnwfactsheet-de.tex
